name: lscache-nestjs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup NestJS environment
        shell: bash
        run: |
          curl -sk -o nodejssetup.sh https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/nodejssetup.sh
          sudo bash nodejssetup.sh
          curl -sk -o per-instance.sh https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Cloud-init/per-instance.sh
          sudo bash per-instance.sh
          pwd
          sudo npm install -g @nestjs/cli
          sudo nest --version
          cd /usr/local/lsws/Example/html/
          sudo rm -rf demo
          sudo nest new demo --package-manager npm
          cd demo
          sudo echo "require('./dist/main');" > app.js
          sudo npm run build; sudo pkill lsnode

          echo 'Download lscach-nestjs'
          sudo npm install git+https://github.com/Code-Egg/lscache-nestjs.git
          
          echo 'Setup test'
          sudo curl -o app/test/test_lscache.py https://raw.githubusercontent.com/Code-Egg/lscache-nestjs/main/tests/test_lscache.js
          echo 'Test'
          sudo node --test test/test_lscache.js